M48
; DRILL file {KiCad 9.0.7} date 2026-04-25T21:32:58+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-25T21:32:58+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.000
%
G90
G05
T1
X132.105Y-97.815
X142.265Y-97.815
T2
X142.24Y-103.307
X142.24Y-105.847
T3
X132.131Y-103.302
X132.131Y-105.842
M30
